"""Build the math eval suite by sampling GSM8K test problems.

Run once at suite-build time. Output is committed to
``eval/suites/golden_v1/math.yaml``; live network is not required at eval time.

Source: GSM8K test split (Cobbe et al., 2021), mirrored as JSONL at
``raw.githubusercontent.com/openai/grade-school-math/master/grade_school_math/data/test.jsonl``.
The full split has 1319 problems; we sample 200 with ``random.Random(42)`` to
keep the suite small enough for CI while large enough for a 2pp regression to
be detectable at the suite level (see ARCHITECTURE.md §drift-statistical-power).

Re-running the script downloads the file once, caches it under
``scripts/data/gsm8k/`` (gitignored), and emits byte-identical YAML.
"""

from __future__ import annotations

import argparse
import json
import pathlib
import random
import sys
import urllib.request

GSM8K_TEST_URL = (
    "https://raw.githubusercontent.com/openai/"
    "grade-school-math/master/grade_school_math/data/test.jsonl"
)

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent
CACHE_DIR = REPO_ROOT / "scripts" / "data" / "gsm8k"
CACHE_FILE = CACHE_DIR / "test.jsonl"
DEFAULT_OUT = REPO_ROOT / "eval" / "suites" / "golden_v1" / "math.yaml"
SAMPLE_SIZE = 200
SEED = 42


def _download() -> None:
    """Cache the GSM8K test JSONL locally. Uses ``urllib`` first; falls back
    to ``curl`` so a stock macOS Python without ``certifi`` can still bootstrap."""
    CACHE_DIR.mkdir(parents=True, exist_ok=True)
    if CACHE_FILE.exists() and CACHE_FILE.stat().st_size > 0:
        return
    req = urllib.request.Request(GSM8K_TEST_URL, headers={"User-Agent": "pulseroute-eval"})
    try:
        with urllib.request.urlopen(req, timeout=60) as resp:  # noqa: S310
            data = resp.read()
    except Exception as exc:  # noqa: BLE001 — broad catch; we fall back to curl
        import shutil
        import subprocess

        if shutil.which("curl") is None:
            raise
        print(f"urllib download failed ({exc}); falling back to curl", file=sys.stderr)
        subprocess.check_call(  # noqa: S603,S607
            ["curl", "-fsSL", GSM8K_TEST_URL, "-o", str(CACHE_FILE)]
        )
        return
    CACHE_FILE.write_bytes(data)


def _load_test_split() -> list[dict[str, str]]:
    with CACHE_FILE.open("r", encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]


def _extract_answer(answer_field: str) -> str:
    """GSM8K stores chain-of-thought in ``answer`` with the final number after
    a ``#### `` marker. Return the marker value verbatim (no rounding)."""
    marker = "#### "
    idx = answer_field.rfind(marker)
    if idx < 0:
        raise ValueError(f"GSM8K record missing '#### ' marker: {answer_field!r}")
    return answer_field[idx + len(marker) :].strip()


def _difficulty(question: str) -> str:
    n = len(question.split())
    if n < 50:
        return "short"
    if n <= 100:
        return "medium"
    return "long"


def _yaml_escape(text: str) -> str:
    """Emit a YAML double-quoted scalar. Escapes backslash, double-quote and
    common control chars; everything else (including unicode) passes through.
    """
    out = []
    for ch in text:
        if ch == "\\":
            out.append("\\\\")
        elif ch == '"':
            out.append('\\"')
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 0x20:
            out.append(f"\\x{ord(ch):02x}")
        else:
            out.append(ch)
    return '"' + "".join(out) + '"'


def render_yaml(samples: list[tuple[int, dict[str, str]]]) -> str:
    """Render the sampled records as a deterministic YAML document.

    Hand-rolled emitter so the output is byte-identical run-to-run regardless
    of the installed PyYAML version's default style heuristics.
    """
    lines: list[str] = [
        "# GSM8K math eval suite for golden_v1.",
        "# Generated by scripts/sample_gsm8k.py — do NOT hand-edit.",
        "# Source: GSM8K test split (Cobbe et al., 2021).",
        f"# Sample: random.Random({SEED}).sample(test_split, {SAMPLE_SIZE}).",
        "# Re-running the script produces byte-identical output.",
        "suite: golden_v1",
        "category: math",
        "scoring: exact_match_numeric",
        f"n_problems: {len(samples)}",
        "problems:",
    ]
    for original_idx, rec in samples:
        question = rec["question"]
        answer = _extract_answer(rec["answer"])
        diff = _difficulty(question)
        lines.append(f'  - id: "gsm8k_test_{original_idx}"')
        lines.append(f"    question: {_yaml_escape(question)}")
        lines.append(f'    answer: "{answer}"')
        lines.append('    source: "gsm8k_test"')
        lines.append(f'    difficulty: "{diff}"')
    return "\n".join(lines) + "\n"


def build(output: pathlib.Path) -> int:
    _download()
    records = _load_test_split()
    if len(records) < SAMPLE_SIZE:
        print(
            f"GSM8K test split too small: got {len(records)} need >= {SAMPLE_SIZE}",
            file=sys.stderr,
        )
        return 1
    rng = random.Random(SEED)
    indices = sorted(rng.sample(range(len(records)), SAMPLE_SIZE))
    samples = [(i, records[i]) for i in indices]
    yaml_text = render_yaml(samples)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(yaml_text, encoding="utf-8")
    print(f"wrote {output} ({len(samples)} problems)")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=pathlib.Path,
        default=DEFAULT_OUT,
        help=f"Output YAML path (default: {DEFAULT_OUT.relative_to(REPO_ROOT)}).",
    )
    args = parser.parse_args()
    return build(args.output)


if __name__ == "__main__":
    sys.exit(main())
